parameters:
  game.player_hit_chance: 0.5
  game.bee_hit_chance: 0.3
  game.delay_between_turns: 0

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      float $playerHitChance: '%game.player_hit_chance%'
      float $beeHitChance: '%game.bee_hit_chance%'
      float $delayBetweenTurns: '%game.delay_between_turns%'

  App\Command\BeesInTheTrapCommand:
    tags: [ 'console.command' ]

  App\Game\AttackServiceInterface: '@App\Game\AttackService'
  App\Game\NarratorServiceInterface: '@App\Game\NarratorService'

  App\Factory\BeeFactory: ~
  App\Entity\Hive:
    arguments: [ '@App\Factory\BeeFactory' ]
  App\Entity\Player: ~
  App\Game\AttackService: ~
  App\Game\NarratorService: ~
  App\Game\GameEngine: ~
